Repository CodeSystem2022/ERROR-404-LABORATORIO3, pull requests merged in 2023-06, with the labels that each got.

#34 Subo clase 9 Herencia JS
  javascript/clase9herencia/Cliente.js
  javascript/clase9herencia/Empleado.js
  javascript/clase9herencia/Persona.js
  javascript/clase9herencia/PruebaPersonas.js
Labels: feature

#36 feature/#8 ramaclase8 subo clase 8 de python
  python/.idea/.gitignore
  python/.idea/clase_07.iml
  python/.idea/inspectionProfiles/profiles_settings.xml
  python/.idea/misc.xml
  python/.idea/modules.xml
  python/base_datos.uxf
  python/capa_datos_persona/Persona.py
  python/capa_datos_persona/__pycache__/logger_base.cpython-39.pyc
  python/capa_datos_persona/capa_datos.log
  python/capa_datos_persona/conexion.py
  python/capa_datos_persona/logger_base.py
  python/capa_datos_persona/persona_dao.py
Labels: feature

#38 feature/10 clase10py Pool python
  python/Clase_08/Persona.py
  python/Clase_08/__pycache__/logger_base.cpython-39.pyc
  python/Clase_08/capa_datos.log
  python/Clase_08/conexion.py
  python/Clase_08/logger_base.py
  python/Clase_08/persona_dao.py
  python/Clase_10/capa_datos_persona/Persona.py
  python/Clase_10/capa_datos_persona/__pycache__/Persona.cpython-310.pyc
  python/Clase_10/capa_datos_persona/__pycache__/conexion.cpython-310.pyc
  python/Clase_10/capa_datos_persona/__pycache__/logger_base.cpython-310.pyc
  python/Clase_10/capa_datos_persona/capa_datos.log
  python/Clase_10/capa_datos_persona/conexion.py
  python/Clase_10/capa_datos_persona/logger_base.py
  python/Clase_10/capa_datos_persona/persona_dao.py
Labels: enhancement, feature

#40 Feat/#39 clase10 js proyecto ventas
  README.md
  javascript/clase10-proyecto-ventas/clases.js
  javascript/clase9herencia/Cliente.js
  javascript/clase9herencia/Empleado.js
  javascript/clase9herencia/Persona.js
Labels: enhancement, feature

#42 Clase11#41 Agrego a conexion.py conectar y cerrar conexión y creo arc…
  python/Clase_11/Persona.py
  python/Clase_11/__pycache__/Persona.cpython-310.pyc
  python/Clase_11/__pycache__/conexion.cpython-310.pyc
  python/Clase_11/__pycache__/logger_base.cpython-310.pyc
  python/Clase_11/capa_datos.log
  python/Clase_11/conexion.py
  python/Clase_11/cursor_del_pool.py
  python/Clase_11/logger_base.py
  python/Clase_11/persona_dao.py
Labels: enhancement
