Repository CodeSystem2022/ERROR-404-LABORATORIO3, pull requests merged in 2023-04, with the labels that each got.

#8 agrego los ejercicios de la clase 2 de javascript de arrays
  javascript/clase2-arreglos/arrays.js
Labels: feature

#9 agrego la clase 3 de JavaScript de funciones
  javascript/clase3-funciones/01-funciones.js
  javascript/clase3-funciones/02-return.js
  javascript/clase3-funciones/03-expresion.js
  javascript/clase3-funciones/04-self-invoking.js
  javascript/clase3-funciones/05-tipo-datos.js
  javascript/clase3-funciones/06-arrow-functions.js
  javascript/clase3-funciones/07-hoisting.js
  javascript/clase3-funciones/08-paso-por-valor.js
  javascript/clase3-funciones/09-paso-por-referencia.js
  javascript/clase3-funciones/README.md
Labels: feature

#10 feature\#1 excepciones- creo las carpetas y hago los ejercicio de la …
  python/Clase_01/Leccion01/.idea/.gitignore
  python/Clase_01/Leccion01/.idea/Leccion01.iml
  python/Clase_01/Leccion01/.idea/inspectionProfiles/Project_Default.xml
  python/Clase_01/Leccion01/.idea/inspectionProfiles/profiles_settings.xml
  python/Clase_01/Leccion01/.idea/misc.xml
  python/Clase_01/Leccion01/.idea/modules.xml
  python/Clase_01/Leccion01/.idea/vcs.xml
  python/Clase_01/Leccion01/NumerosIgualesExcepcion.py
  python/Clase_01/Leccion01/__pycache__/NumerosIgualesExcepcion.cpython-310.pyc
  python/Clase_01/Leccion01/__pycache__/NumerosIgualesExcepcion.cpython-311.pyc
  python/Clase_01/Leccion01/manejo_excepciones.py
Labels: enhancement

#12 agrego la clase 4 de objetos de javascript
  README.md
  javascript/clase4-objetos/01-04-objetos.js
  javascript/clase4-objetos/README.md
  javascript/clase4-objetos/index.html
Labels: feature

#11 facture\#2 clase2- subo clase 2 de python
  python/Clase_02/Leccion2/.idea/.gitignore
  python/Clase_02/Leccion2/.idea/Leccion2.iml
  python/Clase_02/Leccion2/.idea/inspectionProfiles/Project_Default.xml
  python/Clase_02/Leccion2/.idea/inspectionProfiles/profiles_settings.xml
  python/Clase_02/Leccion2/.idea/misc.xml
  python/Clase_02/Leccion2/.idea/modules.xml
  python/Clase_02/Leccion2/.idea/vcs.xml
  python/Clase_02/Leccion2/ManejoArchivos.py
  python/Clase_02/Leccion2/__pycache__/ManejoArchivos.cpython-310.pyc
  python/Clase_02/Leccion2/archivos_con_with.py
  python/Clase_02/Leccion2/copia.txt
  python/Clase_02/Leccion2/leer_archivo.py
  python/Clase_02/Leccion2/manejo_archivos.py
  python/Clase_02/Leccion2/prueba.txt
Labels: good first issue
